# Generated by Django 4.1.2 on 2022-10-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='amt',
            field=models.CharField(default=1000, max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='qty',
            field=models.CharField(default=100, max_length=10),
        ),
    ]
