# Generated by Django 4.1.2 on 2022-10-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
