# Generated by Django 4.1.2 on 2022-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_delete_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=10)),
                ('mark', models.CharField(max_length=2)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
