# Generated by Django 4.1.2 on 2022-10-22 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_fund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fund',
        ),
    ]
