# Generated by Django 4.1.2 on 2022-10-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_delete_fund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=10)),
                ('mark', models.CharField(max_length=4)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
