# Generated by Django 4.1.2 on 2022-10-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
