# Generated by Django 4.1.2 on 2022-10-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_remove_book_authors_remove_book_publish_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
