# Generated by Django 4.1.2 on 2022-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_author_authordetail_publish_book_author_au_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInHand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=10)),
                ('qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
