# Generated by Django 4.1.2 on 2022-11-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_stockinhand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fund',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='amt',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='stockinhand',
            old_name='amt',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='stockinhand',
            old_name='qty',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='qty',
        ),
        migrations.AddField(
            model_name='stock',
            name='mark',
            field=models.CharField(default='买入', max_length=4),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='stockinhand',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stockinhand',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
