# Generated by Django 4.1.2 on 2022-11-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0023_alter_stock_amount_alter_stockinhand_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockProfitbyOp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=10)),
                ('quantity', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=3, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
