# Generated by Django 4.1.2 on 2022-12-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0025_stockprofitbyop_ttlquantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinhand',
            name='profit_todayt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='stockinhand',
            name='ratio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
