# Generated by Django 4.1.2 on 2022-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0026_stockinhand_profit_todayt_stockinhand_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinhand',
            name='ratio',
            field=models.FloatField(),
        ),
    ]
