# Generated by Django 4.1.2 on 2022-12-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0027_alter_stockinhand_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinhand',
            old_name='profit_todayt',
            new_name='profit_today',
        ),
    ]
