# Generated by Django 4.1.2 on 2022-12-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0028_rename_profit_todayt_stockinhand_profit_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinhand',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
