# Generated by Django 4.1.2 on 2022-12-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0029_alter_stockinhand_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='myText',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mytext', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockprofitbyop',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
