# Generated by Django 4.1.2 on 2022-12-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0030_mytext_alter_stock_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PEGData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('name', models.CharField(max_length=10)),
                ('reportqty', models.IntegerField()),
                ('profit_n', models.FloatField()),
                ('profit_n1', models.FloatField()),
                ('profit_n2', models.FloatField()),
                ('profit_n3', models.FloatField()),
                ('GRR', models.FloatField()),
                ('PEttm', models.FloatField()),
                ('PEG', models.FloatField()),
            ],
        ),
    ]
