# Generated by Django 4.1.2 on 2022-12-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0031_pegdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
