# Generated by Django 4.1.2 on 2022-12-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0032_alter_pegdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
