# Generated by Django 4.1.2 on 2022-12-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0033_alter_pegdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegdata',
            name='profit_n',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
