# Generated by Django 4.1.2 on 2022-12-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0035_fruit_alter_pegdata_grr_alter_pegdata_peg_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytext',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.AddField(
            model_name='mytext',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default='2022-12-08 12:22:22.429337'),
            preserve_default=False,
        ),
    ]
