# Generated by Django 4.1.2 on 2022-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0036_alter_mytext_options_mytext_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegdata',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockinhand',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stockprofitbyop',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
