# Generated by Django 4.1.2 on 2022-12-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0037_alter_pegdata_name_alter_stock_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegdata',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinhand',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockprofitbyop',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
