# Generated by Django 4.1.7 on 2023-04-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0040_stock_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mark',
            field=models.CharField(default='B', max_length=4),
        ),
    ]
