# Generated by Django 4.1.7 on 2023-04-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0041_alter_stock_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mark',
            field=models.CharField(default='Buy', max_length=4),
        ),
    ]
