# Generated by Django 4.1.7 on 2023-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0042_alter_stock_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinhand',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
