# Generated by Django 4.1.7 on 2023-04-10 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0043_stockinhand_value_alter_stock_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='au_detail',
        ),
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publish',
        ),
        migrations.DeleteModel(
            name='Fruit',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorDetail',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Publish',
        ),
    ]
