# Generated by Django 4.1.7 on 2023-04-10 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0044_remove_author_au_detail_remove_book_authors_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PEGData',
        ),
    ]
