# Generated by Django 4.1.7 on 2023-04-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0045_delete_pegdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinhand',
            name='value_proportion',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
